"""Add active column to Product

Revision ID: 052d5c5bc951
Revises: 61b571bc24ec
Create Date: 2025-11-12 19:18:49.866240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052d5c5bc951'
down_revision = '61b571bc24ec'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), server_default=sa.true(), nullable=False))

    # 🔹 Виправляємо NULL-значення у category_id, щоб уникнути помилки
    op.execute("UPDATE products SET category_id = 1 WHERE category_id IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('active')

    # ### end Alembic commands ###
