"""Add Category and link to Product

Revision ID: 5e5f903cab7d
Revises: 3167e35afa6e
Create Date: 2025-11-12 19:03:56.066294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5f903cab7d'
down_revision = '3167e35afa6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_products_category",  # ✅ тут ім’я constraint
             "categories",
            ["category_id"],
            ["id"]
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_products_category', type_='foreignkey')
        batch_op.drop_column('category_id')



    op.drop_table('categories')
    # ### end Alembic commands ###
